### Pairwise global sequence alignment

In [ ]:
import numpy as np
import Bio.Align.substitution_matrices

: 

In [2]:
PAM250 = Bio.Align.substitution_matrices.load('PAM250')

In [3]:
aa_list = PAM250.alphabet[:20]

In [4]:
seq1 = "GKVNVDEVGG"
seq2 = "GKVEADIPGHGQEV"

num_rows = len(seq2) + 1
num_cols = len(seq1) + 1

F = np.zeros(shape=(num_rows,num_cols),dtype="int")

T = np.full(shape=(num_rows,num_cols),dtype="str", fill_value=" ")

d = -2 # gap penalty

F[0][0] = 0

for i in range(1, num_rows):
    F[i][0] = F[i-1][0] + d
    
for j in range(1, num_cols):
    F[0][j] = F[0][j-1] + d

In [5]:
T[0][0] = '.'

for i in range(1, num_rows):
    T[i][0] = 'u'
    
for j in range(1, num_cols):
    T[0][j] = 'l'

In [6]:
T

array([['.', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l'],
       ['u', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['u', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['u', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['u', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['u', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['u', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['u', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['u', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['u', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['u', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['u', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['u', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['u', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       ['u', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']],
      dtype='<U1')

In [7]:
F

array([[  0,  -2,  -4,  -6,  -8, -10, -12, -14, -16, -18, -20],
       [ -2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ -4,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ -6,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ -8,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [-10,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [-12,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [-14,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [-16,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [-18,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [-20,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [-22,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [-24,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [-26,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [-28,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [8]:
#match_score = 2
#mismatch_score = -1

for i in range(1, num_rows):
    for j in range(1, num_cols):
        aa_2 = seq2[i-1]
        aa_1 = seq1[j-1]
        aa_2_index = aa_list.find(aa_2)
        aa_1_index = aa_list.find(aa_1)
        if aa_2 == aa_1:
            match_mismatch_score = F[i-1][j-1] + PAM250[aa_2_index][aa_1_index]
        elif aa_2 != aa_1:
            match_mismatch_score = F[i-1][j-1] + PAM250[aa_2_index][aa_1_index]
        
        right_gap_score = F[i][j-1] + d
        left_gap_score = F[i-1][j] + d
        
        F[i,j] = np.max([match_mismatch_score, right_gap_score, left_gap_score])
        which_max = np.argmax([match_mismatch_score, right_gap_score, left_gap_score])
        
        if which_max == 0:
            T[i,j] = 'd' # diagonal
        elif which_max == 1:
            T[i,j] = 'l' # left
        elif which_max == 2:
            T[i,j] = 'u' # up
            
print(F)
print(T)

[[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20]
 [ -2   5   3   1  -1  -3  -5  -7  -9 -11 -13]
 [ -4   3  10   8   6   4   2   0  -2  -4  -6]
 [ -6   1   8  14  12  10   8   6   4   2   0]
 [ -8  -1   6  12  15  13  13  12  10   8   6]
 [-10  -3   4  10  13  15  13  13  12  11   9]
 [-12  -5   2   8  12  13  19  17  15  13  12]
 [-14  -7   0   6  10  16  17  17  21  19  17]
 [-16  -9  -2   4   8  14  15  16  19  21  19]
 [-18 -11  -4   2   6  12  15  15  17  24  26]
 [-20 -13  -6   0   4  10  13  16  15  22  24]
 [-22 -15  -8  -2   2   8  11  14  15  20  27]
 [-24 -17 -10  -4   0   6  10  13  13  18  25]
 [-26 -19 -12  -6  -2   4   9  14  12  16  23]
 [-28 -21 -14  -8  -4   2   7  12  18  16  21]]
[['.' 'l' 'l' 'l' 'l' 'l' 'l' 'l' 'l' 'l' 'l']
 ['u' 'd' 'l' 'l' 'l' 'l' 'l' 'l' 'l' 'd' 'd']
 ['u' 'u' 'd' 'l' 'l' 'l' 'l' 'l' 'l' 'l' 'l']
 ['u' 'u' 'u' 'd' 'l' 'd' 'l' 'l' 'd' 'l' 'l']
 ['u' 'u' 'u' 'u' 'd' 'l' 'd' 'd' 'l' 'l' 'l']
 ['u' 'u' 'u' 'u' 'u' 'd' 'd' 'd' 'd' 'd' 'd']
 ['u' 'u' 'u

In [9]:
direction = ' '

row_index = num_rows - 1 
col_index = num_cols - 1

aln_seq1 = ''
aln_seq2 = ''

while direction != '.':
    direction = T[row_index,col_index]
    
    if direction == 'd':
        row_index = row_index - 1
        col_index = col_index - 1
        aln_seq1 = aln_seq1 + seq1[col_index]
        aln_seq2 = aln_seq2 + seq2[row_index]
        
    elif direction == 'l':
        col_index = col_index - 1
        aln_seq2 = aln_seq2 + '-'
        aln_seq1 = aln_seq1 + seq1[col_index]
        
    elif direction == 'u':
        row_index = row_index - 1
        aln_seq1 = aln_seq1 + '-'
        aln_seq2 = aln_seq2 + seq2[row_index]
        
        
    print(aln_seq1[::-1])
    print(aln_seq2[::-1])

-
V
--
EV
---
QEV
G---
GQEV
-G---
HGQEV
G-G---
GHGQEV
-G-G---
PGHGQEV
V-G-G---
IPGHGQEV
EV-G-G---
-IPGHGQEV
DEV-G-G---
D-IPGHGQEV
VDEV-G-G---
AD-IPGHGQEV
NVDEV-G-G---
EAD-IPGHGQEV
VNVDEV-G-G---
VEAD-IPGHGQEV
KVNVDEV-G-G---
KVEAD-IPGHGQEV
GKVNVDEV-G-G---
GKVEAD-IPGHGQEV
GKVNVDEV-G-G---
GKVEAD-IPGHGQEV
